### ISSUE TITLE
Error while installing kafka-manager

### ISSUE THREAD

**Issue by piyushchordia** [spuder/kafka-manager-cookbook#1]
Hi
While using this repo as an upstream and installing kafka-manager , I am getting below error while running chef

ERROR: kafka_manager[default] (kafka-manager::default line 7) had an error: Chef::Exceptions::Package: yum_package[kafka-manager] (/var/chef/cache/cookbooks/kafka-manager/resources/install.rb line 28) had an error: Chef::Exceptions::Package: No candidate version available for kafka-manager

Using below config
In metadata.rb 
     depends 'kafka-manager','= 0.1.3'
In recipe
     include_recipe 'kafka-manager'
     include_recipe 'kafka-manager::nginx'

Please suggest.

**Comment by spuder** [comment]
Try setting

    node['kafka-manager']['version'] = 1.3.0.4

**Comment by piyushchordia** [comment]
It didnt helped..
Stack Trace 
[[31mError executing action `install` on resource 'yum_package[kafka-manager]'
================================================================================

Chef::Exceptions::Package
-------------------------
No candidate version available for kafka-manager

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/kafka-manager/resources/install.rb

 28:   package 'kafka-manager' do
 29:     version "#{package_version}"
 30:     action :install
 31:   end
 32:

Compiled Resource:
# In /var/chef/cache/cookbooks/kafka-manager/resources/install.rb

 28:   package 'kafka-manager' do
 29:     version "#{package_version}"
 30:     action :install
 31:   end
 32:

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/kafka-manager/resources/install.rb:28:in `block in class_from_file'

yum_package("kafka-manager") do
  package_name "kafka-manager"
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :package
  cookbook_name "kafka-manager"
  flush_cache {:before=>false, :after=>false}
  version "1.3.0.4"
end

Platform:
---------
x86_64-linux


================================================================================
^[[31mError executing action `install` on resource 'kafka_manager[default]'

**Comment by piyushchordia** [comment]
Also can you share URL for RPM file which can be used alternatively

**Comment by spuder** [comment]
Here is where the packages are located. You can compile your own and upload them to your own account on package cloud. 

https://packagecloud.io/spuder/kafka-manager

I've only got a few ubuntu 14.04 and 1 ubuntu 16.04 package, I don't use centOS.
